# Generated by Django 5.1.1 on 2024-10-18 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='producto',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('En espera', 'En espera'), ('En preparacion', 'En preparacion'), ('Listo', 'Listo')], default='En espera', max_length=50),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='option',
            field=models.CharField(choices=[('Para Llevar', 'Para Llevar'), ('Consumir', 'Consumir')], default='Para Llevar', max_length=50),
        ),
    ]
