# Generated by Django 5.1.1 on 2024-10-18 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_pedidos_cantidad_remove_pedidos_nombre_and_more'),
        ('producto', '0002_producto_delete_preparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto'),
        ),
    ]
